---
title: "anova"
author: "Simon Weigold"
date: "2023-07-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE, eval = F}
library(here)
source(here::here("scripts", "preparation.R"))
```

```{r}
anova_avgs <- metrics %>% 
  group_by(collaboration) %>% 
  summarise(avg_streams = mean(streams),
            avg_popularity = mean(popularity, na.rm = T),
            avg_degree = mean(degree),
            avg_betweenness = mean(betweenness),
            avg_closeness = mean(closeness, na.rm = T),
            avg_eigenvector = mean(eigenvector))
```

# Hypothesis 2

```{r}
# cor(metrics$degree, metrics$gs_degree)
# cor(metrics$betweenness, metrics$gs_betweenness)
# cor(metrics$closeness, metrics$gs_closeness, use = "na.or.complete")
# cor(metrics$eigenvector, metrics$gs_eigenvector)
```

```{r}
# ANOVA streams
#stats::oneway.test(AV ~ Gruppe, data = Daten)
#stats::oneway.test(popularity ~ collaboration, data = metrics)
```

Levene Test for variance homogeneity
https://bjoernwalther.com/levene-test-in-r-berechnen-und-interpretieren/
```{r}
leveneTest(aov)
```
Shapiro-Wilk test for normality of residuals
https://bjoernwalther.com/shapiro-wilk-test-in-r-rechnen/
```{r}
shapiro.test(metrics$popularity)
```


One-way ANOVA
```{r}
aov <- aov(popularity ~ collaboration, data = metrics)
summary(aov)
```

Homoscedasticity
```{r}
par(mfrow = c(2,2))
plot(aov)
par(mfrow = c(1,1))
```

post-hoc test
```{r}
tukey.two.way <- TukeyHSD(aov)
tukey.two.way
```
```{r}
par(family = "serif")
plot(TukeyHSD(aov), las = 1)
```

```{r}
ggplot(metrics, aes(x = collaboration, y = popularity, group = collaboration)) +
  geom_point(cex = 1.5, pch = 1.0, position = position_jitter(w = 0.1, h = 0),
             colour = "royalblue", alpha = 0.75) +
  xlab("") +
  #stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = 0.2) +
  stat_summary(fun.data = 'mean_se', geom = 'point', colour = "black", shape = 18, size = 2) +
  theme(axis.text = element_text(color="black", size=12, family="serif"),
        axis.text.x = element_text(color="black", size=12, family="serif"),
        axis.ticks.x = element_line(),
        axis.ticks.y = element_line(),
        axis.line.x = element_line(linewidth=0.5, color="grey"),
        axis.line.y = element_line(linewidth=0.5, color="grey"),
        panel.grid = element_line(color = "honeydew2",
                                  size = 0.5,
                                  linetype = 1),
        panel.background = element_rect(fill="white"),
        plot.margin = margin(10,10,10,10),
        plot.title = element_text(color="black", size=16, family="serif"),
        plot.subtitle = element_text(color="grey26", size=14, family="serif"),
        legend.text = element_text(color="black", size=12, family="serif"),
        text = element_text(color="black", size=14, family="serif")
  )
```


